# Generated by Django 5.0 on 2023-12-20 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('director', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Mistery', 'Mistery'), ('Romance', 'Romance'), ('Thriller', 'Thriller')], default=None, max_length=255)),
                ('is_favorite', models.ManyToManyField(blank=True, related_name='favorite_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
