# Generated by Django 5.0 on 2023-12-21 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='created_by',
            new_name='user',
        ),
    ]
