# Generated by Django 5.0 on 2023-12-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_rename_created_by_movie_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='movie',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
