# Generated by Django 5.0 on 2023-12-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_rating_movie_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='movie',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
