# Generated by Django 5.0 on 2023-12-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_remove_movie_average_rating_remove_movie_ratings_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
