# Generated by Django 5.0 on 2023-12-25 11:56

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Mistery', 'Mistery'), ('Romance', 'Romance'), ('Thriller', 'Thriller')], max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, verbose_name='DESCRIPTION'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=255, verbose_name='DIRECTOR'),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='RELEASE DATE'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='TITLE'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title', 'director'], name='movie_movie_title_c54524_idx'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='movie.genre'),
        ),
    ]
