# Generated by Django 5.0 on 2023-12-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_alter_movie_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Mistery', 'Mistery'), ('Romance', 'Romance'), ('Thriller', 'Thriller')], verbose_name='GENRE'),
        ),
    ]
