# Generated by Django 5.0 on 2023-12-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0020_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Mistery', 'Mistery'), ('Romance', 'Romance'), ('Thriller', 'Thriller')], max_length=12, null=True, verbose_name='GENRE'),
        ),
    ]
