# Generated by Django 5.0 on 2023-12-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0021_alter_movie_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
