# Generated by Django 5.0 on 2023-12-25 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0022_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
