# Generated by Django 5.0 on 2023-12-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0024_genre_remove_movie_genre_movie_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=None, verbose_name='RELEASE DATE'),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Mistery', 'Mistery'), ('Romance', 'Romance'), ('Thriller', 'Thriller')], default=None, max_length=20, verbose_name='GENRE'),
        ),
    ]
