# Generated by Django 5.0 on 2023-12-25 16:16

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0026_alter_movie_release_date_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 25, 16, 16, 18, 687989, tzinfo=datetime.timezone.utc), verbose_name='RELEASE DATE'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
