# Generated by Django 5.0 on 2023-12-26 19:47

import datetime
import movie.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0027_alter_movie_release_date_alter_rating_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='movie',
            name='movie_movie_title_c54524_idx',
        ),
        migrations.AddField(
            model_name='movie',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to=movie.utils.user_directory_path, verbose_name='COVER IMAGE'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 26, 19, 47, 34, 708535, tzinfo=datetime.timezone.utc), verbose_name='RELEASE DATE'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title', 'director', 'genre'], name='movie_movie_title_0381bc_idx'),
        ),
    ]
