# Generated by Django 5.0 on 2023-12-26 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0030_alter_movie_release_date_alter_movie_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 26, 22, 21, 4, 174311, tzinfo=datetime.timezone.utc), verbose_name='RELEASE DATE'),
        ),
    ]
