# Generated by Django 5.0 on 2023-12-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_userprofile_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='photo',
        ),
        migrations.AlterField(
            model_name='locationuser',
            name='city',
            field=models.CharField(choices=[('SF', 'Sofia'), ('V', 'Varna'), ('PD', 'Plovdiv'), ('BU', 'Burgas'), ('PN', 'Pleven'), ('VR', 'Vraca'), ('M', 'Montana')], default='Sofia', max_length=64),
        ),
    ]
