# Generated by Django 5.0 on 2023-12-27 16:38

import user.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_userprofile_photo_alter_locationuser_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo_profile',
            field=models.ImageField(blank=True, upload_to=user.utils.user_directory_path),
        ),
    ]
